AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
  Exclude:
    - '**/bin/**/*'
    - 'vendor/**/*'
    - 'gemfiles/vendor/**/*'
    - 'spec/dummy/db/schema.rb'
    - 'db/**/*'
    - 'test/**/**/*'
    - 'config/**/**/*'
    - 'Backup/**/*'

Rails:
  Enabled: true

Rails/Validation:
  Enabled: false

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedLastArgumentHashStyle: always_ignore

Style/BracesAroundHashParameters:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/IndentHash:
  EnforcedStyle: consistent

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Next:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/SignalException:
  EnforcedStyle: only_raise

Style/NumericLiterals:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Rails/HttpPositionalArguments:
  Enabled: false
