language: ruby
sudo: required
bundler_args: "--jobs=4 --retry=3"
cache: bundler
services:
- elasticsearch
before_script:
- sleep 10
after_success:
- chmod 600 deploy-key
- mv deploy-key ~/.ssh/id_rsa
- cap deploy staging
before_install:
- openssl aes-256-cbc -K $encrypted_bde597b39305_key -iv $encrypted_bde597b39305_iv
  -in deploy_key.enc -out deploy_key -d
- echo -e "Host example.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
