SECRET_KEY_BASE: "thisisasupersecret"
DEVISE_PEPPER: "anothersupersecret"
WUFOO_HANDSHAKE_KEY: "somekindahandshake"
TWILIO_API_SID: ""
TWILIO_AUTH_TOKEN: ""
TWILIO_SIGNUP_NUMBER: ""
TWILIO_SIGNUP_VERIFICATION_NUMBER: ""
TWILIO_SURVEY_NUMBER: ""
TWILIO_SCHEDULING_NUMBER: ""
WUFOO_ACCOUNT: ""
WUFOO_API: ""
MAILCHIMP_API_KEY: ""
MAILCHIMP_LIST_ID: ""
MAILCHIMP_WEBHOOK_SECRET_KEY: ""
PRODUCTION_SERVER: ""
PRODUCTION_BRANCH: ""
STAGING_SERVER: ""
STAGING_BRANCH: ""
TIME_ZONE: "Eastern Time (US & Canada)"
MAILER_SENDER: ""
MAIL_ADMIN: ""
MANDRILL_USERNAME: ""
MANDRILL_API_KEY: ""
GROUP_NAME: ""
GOOGLE_API_KEY: ""
GOOGLE_ANALYTICS_APP_ID: ""
GOOGLE_ANALYTICS_SIGNUP_ID: ""
FACEBOOK_PIXEL_ID: ""
VERIFICATION_SMS_MESSAGE: "Thank you for verifying your account. We will mail you your $5 VISA gift card right away."
SIGNUP_EMAIL_MESSAGE: "You are now signed up for Cohorts! Your $5 gift card will be in the mail. When new tests come up, you'll receive an email from smarziano@cct.org with details."
SIGNUP_SMS_MESSAGE: "You are now signed up for Cohorts! Your $5 gift card will be in the mail. When new tests come up, you'll receive a text from 773-747-6239 with more details."
SIGNUP_ERROR_MESSAGE: "If you are having trouble email smarziano@cct.org or text '98765' and you will be contacted later."
